name: Build UI
on:
  push:
    branches:
      - main
      - cicd/build

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: oven/bun:debian
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: build ui
        run: cd ui && bun install && bun run build

      - name: deploy to gh-pages
        run: |
          git worktree add -B gh-pages gh-pages origin/gh-pages
          cp -r ui/dist/* gh-pages/
          cd gh-pages && git add . && git commit -m "Update gh-pages" && git push origin gh-pages